# yazi.toml
[manager]
show_hidden = true
show_mtime = true
linemode = "size_and_mtime"

[preview]
max_width = 1800
max_height = 1800
pdf_thumbnails = true # Enable PDF thumbnails

[preview.mime]
"video/*" = "ffmpegthumbnailer -i {path} -o {cache} -s 0 -t 10 && cat {cache}"
